version: "3"

services:
  dxc-server:
    image: databrokerdao/dxc-multi-arch:latest
    volumes:
      - ./db-data:/go/db-data
    ports:
      - "8181:8080"
    restart: on-failure
    env_file:
      - ./.env
  dxc-ui:
    image: databrokerdao/dxc-ui-multi-arch:latest
    ports:
      - "8282:80"
    env_file:
      - ./.env
    restart: on-failure